DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Thread;
DROP TABLE IF EXISTS Comment;

CREATE TABLE User (
    idUser      INTEGER  NOT NULL PRIMARY KEY,
    username	VARCHAR (100) NOT NULL,
	password	VARCHAR (100) NOT NULL,
	age 		INTEGER NOT NULL,
	mail		VARCHAR (100) NOT NULL
	
);

CREATE TABLE Thread (
	idThread	INTEGER NOT NULL PRIMARY KEY,
	Title 		VARCHAR (100) NOT NULL

);

CREATE TABLE Comment (
	idComment	INTEGER NOT NULL PRIMARY KEY,
	idThread 	INTEGER REFERENCES Thread (idThread),
	Text		VARCHAR (500) NOT NULL,
	Upvotesq	INTEGER,
	Downvotes	INTEGER
);